spring.application.name=pos-system

# --- Konfiguracja Bazy Danych H2 (w pami?ci) ---
spring.datasource.url=jdbc:h2:mem:posdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# --- Konfiguracja JPA / Hibernate ---
# To sprawia, ?e Spring sam tworzy tabelki na podstawie Twoich klas Java
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# --- Magiczna Konsola H2 ---
# Dzi?ki temu b?dziesz móg? wej?? przez przegl?dark? do bazy danych
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console